logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]

  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]

# Email address used for registration
email = "ulhas+tbs@theprocedure.in"
storage = "./acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

[file]

[backends]
  [backends.viewer]
    [backends.viewer.servers.server1]
      url = "http://localhost:3030"
  [backends.reader]
    [backends.reader.servers.server1]
      url = "http://localhost:8080"
  [backends.block]
    [backends.block.servers.server1]
      url = "http://localhost:25001"

[frontends]
  [frontends.block]
    backend = "block"
    [frontends.block.routes.dr1]
      rule = "Host:api.staging.***.***.co;Path:/"
  [frontends.reader]
    backend = "reader"
    [frontends.reader.routes.dr1]
      rule = "Host:api.staging.***.***.co;PathPrefix:/dcm4chee-arc/"
  [frontends.viewer]
    backend = "viewer"
    [frontends.viewer.routes.dr1]
      rule = "Host:api.staging.***.***.co"